EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs
EvidenceApi/V1/Controllers/DocumentSubmissionsController.cs
EvidenceApi/V1/Controllers/EvidenceRequestsController.cs

Moves PATCH DocumentSubmissions to top level, as the frontend doesn't always have access to the evidence request ID.
This will also make it easier when we need GET for the same resource.

Move PATCH document_submissions to top level

---

EvidenceApi/serverless.yml

I have converted our "secret" SSM params from type String to type SecureString, so that they are encrypted at rest.
We need to tell serverless to decrypt them before injecting them as environment variables, otherwise we will get the encrypted value.
It seems that terraform does this by default.

Decrypt SSM params of type SecureString

---

terraform/staging/main.tf

because encryption is not supported on db.t2.micro
Raised this after HackIT folks enabled encryption on _all_ databases with https://github.com/LBHackney-IT/aws-hackney-common-terraform/pull/29/files
And we saw issues in CircleCI: https://app.circleci.com/pipelines/github/LBHackney-IT/evidence-api/211/workflows/dc897ce1-2ffb-4c53-8fda-9ea9e20052cc/jobs/815:
```
Error: Error creating DB Instance: InvalidParameterCombination: DB Instance class db.t2.micro does not support encryption at rest
status code: 400, request id: 9df05d07-c6cf-45ea-a569-c4b5f1d63979
```

Bump the db instance size 

---

EvidenceApi.Tests/V1/E2ETests/EvidenceRequestsTest.cs
EvidenceApi.Tests/V1/E2ETests/ResidentsTests.cs
EvidenceApi.Tests/V1/Factories/ResponseFactoryTest.cs
EvidenceApi.Tests/V1/Gateways/EvidenceGatewayTests.cs
EvidenceApi.Tests/V1/UseCase/CreateEvidenceRequestUseCaseTests.cs
EvidenceApi.Tests/V1/UseCase/FindResidentsBySearchQueryUseCaseTests.cs
EvidenceApi/V1/Boundary/Request/ResidentSearchQuery.cs
EvidenceApi/V1/Boundary/Response/EvidenceRequestResponse.cs
EvidenceApi/V1/Boundary/Response/ResidentResponse.cs
EvidenceApi/V1/Controllers/EvidenceRequestsController.cs
EvidenceApi/V1/Controllers/ResidentsController.cs
EvidenceApi/V1/Factories/ResponseFactory.cs
EvidenceApi/V1/Gateways/EvidenceGateway.cs
EvidenceApi/V1/Gateways/Interfaces/IEvidenceGateway.cs
EvidenceApi/V1/UseCase/FindResidentsBySearchQueryUseCase.cs
EvidenceApi/V1/UseCase/Interfaces/IFindResidentsBySearchQueryUseCase.cs

https://hackney.atlassian.net/browse/DES-75
- `GET:resident/search` now takes `ServiceRequestedBy` and `SearchQuery`
- This ensures we only retrieve residents for the provided service
- Move `ResidentReferenceId` from `EvidenceRequestResponse` to `ResidentResponse` because it's related to the resident
- Search `residents` table for the `SearchQuery` first, then `evidence_requests` for the resident reference ID, and return all matches

DES-75: search for a resident by reference number

---

.circleci/config.yml

We should deploy the app only if database migration finishes successfully, otherwise we may deploy code changes that depend on database changes which weren't deployed

DES-253: app deployment should be dependent on database migration

---

EvidenceApi/V1/Boundary/Response/Exceptions/NotificationException.cs
EvidenceApi/V1/Controllers/EvidenceRequestsController.cs
EvidenceApi/V1/UseCase/CreateEvidenceRequestUseCase.cs
EvidenceApi/V1/UseCase/UpdateDocumentSubmissionStateUseCase.cs

https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-221
Updated the custom exception thrown when gov notify fails to send the notification via one of the delivery methods. By doing this we can pass to the frontend a more meaningful error message so the user understands what's going wrong.

Improve the exception thrown by gov notify

---

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs
EvidenceApi.Tests/V1/Factories/ResponseFactoryTest.cs
EvidenceApi.Tests/V1/Gateways/DocumentsApiGatewayTests.cs
EvidenceApi.Tests/V1/UseCase/CreateDocumentSubmissionUseCaseTests.cs
EvidenceApi/V1/Boundary/Request/DocumentSubmissionRequest.cs
EvidenceApi/V1/Boundary/Response/DocumentSubmissionResponse.cs
EvidenceApi/V1/Controllers/EvidenceRequestsController.cs
EvidenceApi/V1/Factories/ResponseFactory.cs
EvidenceApi/V1/Gateways/DocumentsApiGateway.cs
EvidenceApi/V1/Gateways/Interfaces/IDocumentsApiGateway.cs
EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs
EvidenceApi/V1/UseCase/FindDocumentSubmissionByIdUseCase.cs
EvidenceApi/V1/UseCase/FindDocumentSubmissionsByResidentIdUseCase.cs
EvidenceApi/V1/UseCase/Interfaces/ICreateDocumentSubmission.cs

https://hackney.atlassian.net/browse/DES-309
- The document is now provided when we create the Document Submission
- This is sent to DocumentsApi to be uploaded. PR for that - LBHackney-IT/documents-api/pull/86
- Document Submission is in _uploaded_ state
- This supersedes #85 which had wip code

DES-309: forward multipart uploads from the frontend to DocumentsAPI

---

EvidenceApi/serverless.yml

Removed ~true from the SSM parameters based on the guidance received in the warning of the previous CircleCI build

Fix ssm parameters by removing ~true

---

EvidenceApi.Tests/TestDataHelper.cs
EvidenceApi.Tests/V1/Gateways/NotifyGatewayTests.cs
EvidenceApi/V1/Gateways/NotifyGateway.cs
EvidenceApi/V1/UseCase/CreateEvidenceRequestUseCase.cs

https://hackney.atlassian.net/browse/DOC-682
This PR should only be merged when the entire feature is ready to be released to production! Once released to production the `Request for evidence` GOV Notify template for both email and sms should be updated based on `Request for evidence (test)` template. This update should be done ASAP after releasing to production to reduce the time the template doesn't match the backend.
- Added new parameter `note_to_resident` to the list of parameters to be used by GOV Notify template `Request for evidence`
- Updated the helper method that creates an evidence request in `CreateEvidenceRequestUseCase` to set a default value for `NoteToResident` when it's empty
- Updated test helper method to create an evidence request that contains a value for …

Add note_to_resident parameter to the request evidence template

---

EvidenceApi/DocumentTypes.json
EvidenceApi/StaffSelectedDocumentTypes.json

Linked to this ticket: https://hackney.atlassian.net/browse/DOC-564
Added onboarding information for Tenancy and Leaseholds team. 
> Finished adding the config!)
Please check with Lewis the team name before merging. 
> They would like to be called Leasehold and Right to Buy
Also, this PR should be merged at the same time as the PR containing the onboarding information in the frontend.
> PR for the frontend exists -- being reviewed.

Add onboarding information for tenancy and leaseholds team

---

EvidenceApi/DocumentTypes.json
EvidenceApi/StaffSelectedDocumentTypes.json

https://hackney.atlassian.net/browse/DOC-810
As part of their onboarding, Leasehold and Right to Buy have requested that we change their config to make the requested documents more specific i.e. not 'proof of id', but 'passport'. This commit makes those specific types available, but officers will still need to confirm another time what type they are when they go to approve the document.
Replaced the previous document types with new ones. This requires a wipe of all Leasehold and Right to Buy evidence requests in staging, as missing ids from previous evidence requests (e.g. proof-of-id) will cause the request page to crash.
For ref, the onboarding info can be found here: https://docs.google.com/spreadsheets/d/1x0lurLL9n_NgxE-Z4-SSjYRf0ixfBreDkIy6EGN7T3M/edit#gid=482343803
Check that …

Change config for Leasehold and Right to Buy to make docs more specific

---

EvidenceApi/serverless.yml

https://hackney.atlassian.net/browse/DOC-843
Updated the names of the SSM parameters in serverless to include the name of the stage. This helps referencing the correct name for the template based on the stage.

Update serverless parameter names for gov notify templates

---

.circleci/config.yml

No ticket!
CircleCI fails because the was a recent patch to dotnet-ef and our pipeline fails with this error:
Update config to lock version to 6.0.5, the last working version for us.

Add version specification to lock dotnet-ef to 6.0.5

---

EvidenceApi.Tests/TestDataHelper.cs
EvidenceApi.Tests/V1/Gateways/NotifyGatewayTests.cs
EvidenceApi/V1/Gateways/NotifyGateway.cs

https://hackney.atlassian.net/browse/DOC-846
HR have identified that they would like the resident to be able to see what types of documents have been requested from them before they get onto the page where they need to upload the documents to DES. After discussion with the team, we decided that the place place to put this information (for now) is in the email.
As part of the evidence request creation, we request Gov Notify to send an email and SMS to the resident. As part of this request to Gov Notify, we send a dictionary of keys and data to display in the message template. I've added a new key called 'document_types' to include a string of all of the documentTypes that are part of the evidence request.
Here is what the old templates look like:
Here is what the new templates look like:
I …

Show what types of documents were requested in evidence request in first email to resident

---

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs
EvidenceApi.Tests/V1/E2ETests/EvidenceRequestsTest.cs
EvidenceApi.Tests/V1/UseCase/CreateDocumentSubmissionUseCaseTests.cs
EvidenceApi.Tests/V1/UseCase/SendNotificationUploadConfirmationToResidentAndStaffTests.cs
EvidenceApi/Startup.cs
EvidenceApi/V1/Controllers/EvidenceRequestsController.cs
EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs
EvidenceApi/V1/UseCase/Interfaces/ISendNotificationUploadConfirmationToResidentAndStaff.cs
EvidenceApi/V1/UseCase/SendNotificationUploadConfirmationToResidentAndStaff.cs
EvidenceApi/V1/UseCase/SendUploadConfirmationToResidentUseCase.cs
EvidenceApi/V1/UseCase/UpdateEvidenceRequestStateUseCase.cs

https://hackney.atlassian.net/browse/DOC-905
At the moment, officers receive an email per document submission. So if a resident uploads 15 documents, the staff member will receive 15 emails. Not great, so we needed to reduce the amount that are sent.
I've added the new line of code so an existing endpoint so that when a resident clicks 'submit', it sends an email to the staff member (as well as a confirmation to the resident). This required a lot of renaming and I've updated the tests to capture this change. I've removed `ConfigureAwait(true)` in the relevant files, because we're suppressing that error. I've also done some refactoring of the CreateDocumentSubmission tests, as they were in a different file. 
The new behaviour is now whenever a resident clicks 'submit', one email is sent to …

Officer to receive one email per upload from resident

---

EvidenceApi/V1/Gateways/NotifyGateway.cs

https://hackney.atlassian.net/browse/DOC-735
Previously, after a resident uploaded multiple documents, if the staff member rejected any of them the email to resident will mention that a different document was rejected instead of the correct one. This PR fixes that bug and now properly displays in the email to the resident the document that was rejected.

Fix rejected document mentioning the wrong document in the email

---

EvidenceApi.Tests/V1/UseCase/SendNotificationUploadConfirmationToResidentAndStaffTests.cs
EvidenceApi/V1/UseCase/SendNotificationUploadConfirmationToResidentAndStaff.cs

When documents are uploaded, staff members are notified by email that someone has uploaded documents. When both email and SMS options were selected for an evidence request the system was also trying to send an SMS to the staff member but wasn't able to find a GovNotify template (as there shouldn't be one). This fix makes the call to the GovNotify gateway to send only an email notification to staff regardless of the delivery method selected in the evidence request creation step.

Bug fix for trying to send an SMS to notify staff members when documents are uploaded

---

EvidenceApi/V1/Gateways/DocumentsApiGateway.cs

https://hackney.atlassian.net/browse/DOC-1082
Decreased the number of throttled requests to 10 and added a 200ms delay in between requests. This was done in order to try and reduce the pressure on the lambda authorizer dynamo db read capacity which is currently limited to 10 read units.

Decrease SemaphoreSlim number of throttled requests and add delay

---

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs
EvidenceApi.Tests/V1/E2ETests/EvidenceRequestsTest.cs
EvidenceApi.Tests/V1/Factories/ResponseFactoryTest.cs
EvidenceApi/V1/Boundary/Response/DocumentSubmissionResponse.cs
EvidenceApi/V1/Factories/ResponseFactory.cs
EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs
EvidenceApi/V1/UseCase/FindDocumentSubmissionByIdUseCase.cs
EvidenceApi/V1/UseCase/FindDocumentSubmissionsByResidentIdUseCase.cs
EvidenceApi/V1/UseCase/UpdateDocumentSubmissionStateUseCase.cs

https://hackney.atlassian.net/browse/DOC-852
Add `evidenceRequestId` to the `DocumentSubmissionResponse` so that we can associate evidence requests with document submissions in the frontend. This is useful for identifying the document types that haven't been submitted yet.

Add evidenceRequestId to DocumentSubmissionResponse

---

EvidenceApi/DocumentTypes.json
EvidenceApi/StaffSelectedDocumentTypes.json

Part of the testing for this ticket 
https://hackney.atlassian.net/browse/DOC-872
I've made an evidence request with 2 x proof of address and approved one to be utility bills. If we disable those types, we should still be able to view the documents, but not select them for any new evidence requests.
I've set proof of address and utility bills for the dev housing team to be false.
See if I can view documents. Try to make new evidence request and check if the doc types are there or not.

Disable new dev config doc types

---

EvidenceApi.Tests/V1/UseCase/UpdateDocumentSubmissionStateUseCaseTests.cs

https://hackney.atlassian.net/browse/DOC-1167
The compiler was  flagging a warning in two tests as the methods being called were asynchronous but the tests were returning void and not awaiting the response of the calls (warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.)
This PR aims to correct that.
Changes in two tests

calling async functions within tests

---

EvidenceApi.Tests/V1/E2ETests/EvidenceRequestsTest.cs
EvidenceApi.Tests/V1/UseCase/CreateDocumentSubmissionUseCaseTests.cs
EvidenceApi/V1/Boundary/Response/DocumentSubmissionResponse.cs
EvidenceApi/V1/Factories/ResponseFactory.cs
EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs

https://hackney.atlassian.net/jira/software/c/projects/DOC/boards/68?modal=detail&selectedIssue=DOC-1306
To enable us to allow teams to be linked to document submissions as well as evidence requests, the requesting team must be populated on the document submission. This is part of a larger piece of work to allow document submissions without evidence requests. This change is not breaking.
Added mapping and tests to map the team requesting the evidence to the document submission itself.

DOC-1306 - Include Team on Document Submission

---

EvidenceApi.Tests/V1/E2ETests/EvidenceRequestsTest.cs
EvidenceApi.Tests/V1/UseCase/CreateDocumentSubmissionUseCaseTests.cs
EvidenceApi/V1/Boundary/Response/DocumentSubmissionResponse.cs
EvidenceApi/V1/Factories/ResponseFactory.cs
EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs

https://hackney.atlassian.net/browse/DOC-1322
This PR aims to save the resident_id not only on the evidence_requests table but also on the new resident_id column for document_submission, in the context of enabling the users to upload on behalf of residents.
This is a non breaking change. 
Added new field in the appropriate UseCase and responses

DOC-1322 - Adding ResidentId to DocumentSubmissions

---

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs
EvidenceApi.Tests/V1/E2ETests/EvidenceRequestsTest.cs
EvidenceApi.Tests/V1/UseCase/CreateDocumentSubmissionWithoutEvidenceRequestUseCaseTests.cs
EvidenceApi/V1/Boundary/Request/ClaimRequest.cs
EvidenceApi/V1/Boundary/Request/DocumentSubmissionWithoutEvidenceRequestRequest.cs
EvidenceApi/V1/Domain/Claim.cs
EvidenceApi/V1/UseCase/CreateDocumentSubmissionWithoutEvidenceRequestUseCase.cs
EvidenceApi/V1/Validators/DocumentSubmissionWithoutEvidenceRequestRequestValidator.cs

https://hackney.atlassian.net/browse/DOC-1279
Remove `DocumentName` from request to create document submission without an evidence request as there is no way to add a value for it at the moment.

Remove DocumentName from request to create document submission without evidence request

---

.circleci/config.yml
EvidenceApi.Tests/Dockerfile
EvidenceApi.Tests/EvidenceApi.Tests.csproj
EvidenceApi.Tests/GlobalSetup.cs
EvidenceApi.Tests/V1/Controllers/HealthCheckControllerTests.cs
EvidenceApi.Tests/V1/E2ETests/HealthCheckTests.cs
EvidenceApi.Tests/V1/Gateways/EvidenceGatewayTests.cs
EvidenceApi.Tests/V1/UseCase/EvidenceRequestValidatorTests.cs
EvidenceApi/Dockerfile
EvidenceApi/EvidenceApi.csproj
EvidenceApi/Startup.cs
EvidenceApi/V1/Boundary/Request/DocumentSubmissionUpdateRequest.cs
EvidenceApi/V1/Boundary/Request/EvidenceRequestsSearchQuery.cs
EvidenceApi/V1/Gateways/EvidenceGateway.cs
EvidenceApi/V1/Gateways/ResidentsGateway.cs
EvidenceApi/build.sh
EvidenceApi/serverless.yml
README.md
database/Dockerfile

https://hackney.atlassian.net/jira/software/c/projects/DOC/boards/68?modal=detail&selectedIssue=DOC-1076
This PR upgrades the Evidence API to run on Dotnet 6, replacing Dotnet 3.1 which is coming to end of life. Packages have been upgraded, and refactoring has been done where methods are no longer supported.

DOC-1076 - Upgrade To Dotnet 6

---

EvidenceApi/V1/UseCase/CreateDocumentSubmissionWithoutEvidenceRequestUseCase.cs

[DOC-1375](https://hackney.atlassian.net/browse/DOC-1375)
When uploading a document on behalf of, documents are auto-approved. The uploading user isn't however saved as the approver. This PR addresses that.
Data (email) is already coming into the API. Documents already uploaded on behalf of will still have an empty approver.
Single line change.
- [-] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [-] Added tests to cover all new production code
- [-] Code pipeline builds correctly
Check in staging

Add user updated by value for internally submitted documents

---

EvidenceApi.Tests/V1/UseCase/FindResidentsBySearchQueryUseCaseTests.cs
EvidenceApi/V1/UseCase/FindResidentsBySearchQueryUseCase.cs

https://hackney.atlassian.net/jira/software/c/projects/DOC/boards/68?modal=detail&selectedIssue=DOC-1376
This alters the resident search use case to allow for residents who do not have a linked evidence request.
Modified the resident search use case.

DOC-1376 - Adjust Search To Allow Searching For Residents Without Related Document Submissions / Evidence Requests

---

EvidenceApi/Migrations/20230123150743_createResidentGroupIdMetaTable.Designer.cs
EvidenceApi/Migrations/20230123150743_createResidentGroupIdMetaTable.cs
EvidenceApi/V1/Domain/ResidentsTeamGroupId.cs
EvidenceApi/V1/Infrastructure/EvidenceContext.cs

https://hackney.atlassian.net/jira/software/c/projects/DOC/boards/68?modal=detail&selectedIssue=DOC-1395
This PR creates a new table, used to associate resident_ids and group_ids.
Added new table to associate residents and group ids. NB this table also includes a 'created_at' column in order to conform to the IEntity Interface used by the other database tables.

DOC-1395 - Create Table To Link Resident Ids and Group Ids

---

EvidenceApi/Migrations/20230130095730_EnableLegacyTimestamp.Designer.cs
EvidenceApi/Migrations/20230130095730_EnableLegacyTimestamp.cs
EvidenceApi/Startup.cs

https://hackney.atlassian.net/browse/DOC-1410
This PR fixes the misconfiguration of the legacy timestamp behaviour.
BI does not expect the timestamps to be created with a timezone. Therefore we need to enable legacy behaviour on the postgres data type.
Ensured that the configuration option for legacy timestamps is set before the database is configured. Run a migration to adjust the data types.

DOC-1410 - Legacy Timestamps

---

EvidenceApi.Tests/V1/E2ETests/BaseControllerTests.cs
EvidenceApi.Tests/V1/E2ETests/EvidenceRequestsTest.cs
EvidenceApi.Tests/V1/E2ETests/ResidentsTests.cs
EvidenceApi.Tests/V1/Gateways/ResidentsGatewayTests.cs
EvidenceApi.Tests/V1/UseCase/CreateDocumentSubmissionUseCaseTests.cs
EvidenceApi.Tests/V1/UseCase/CreateDocumentSubmissionWithoutEvidenceRequestUseCaseTests.cs
EvidenceApi.Tests/V1/UseCase/CreateEvidenceRequestUseCaseTests.cs
EvidenceApi.Tests/V1/UseCase/CreateResidentUseCaseTests.cs
EvidenceApi.Tests/V1/UseCase/EvidenceRequestValidatorTests.cs
EvidenceApi.Tests/V1/UseCase/ResidentRequestValidatorTests.cs
EvidenceApi/V1/Boundary/Request/ClaimRequest.cs
EvidenceApi/V1/Boundary/Request/ResidentRequest.cs
EvidenceApi/V1/Gateways/Interfaces/IResidentsGateway.cs
EvidenceApi/V1/Gateways/ResidentsGateway.cs
EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs
EvidenceApi/V1/UseCase/CreateDocumentSubmissionWithoutEvidenceRequestUseCase.cs
EvidenceApi/V1/UseCase/CreateEvidenceRequestUseCase.cs
EvidenceApi/V1/UseCase/CreateResidentUseCase.cs

https://hackney.atlassian.net/browse/DOC-1402
Updated all use cases that are creating document submissions to check for the existence of a `groupId` for a resident for a team in `residents_team_group_id` table and if no record is found a new entry is added with a fresh `groupId`.

Add groupId to all upload flows

---

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs
EvidenceApi.Tests/V1/Gateways/DocumentsApiGatewayTests.cs
EvidenceApi.Tests/V1/Gateways/ResidentsGatewayTests.cs
EvidenceApi.Tests/V1/UseCase/FindDocumentSubmissionsByResidentIdUseCaseTests.cs
EvidenceApi/V1/Boundary/Request/PaginatedClaimRequest.cs
EvidenceApi/V1/Domain/PaginatedClaimResponse.cs
EvidenceApi/V1/Domain/ResidentsTeamGroupId.cs
EvidenceApi/V1/Gateways/DocumentsApiGateway.cs
EvidenceApi/V1/Gateways/Interfaces/IDocumentsApiGateway.cs
EvidenceApi/V1/Gateways/Interfaces/IResidentsGateway.cs
EvidenceApi/V1/Gateways/ResidentsGateway.cs
EvidenceApi/V1/UseCase/FindDocumentSubmissionsByResidentIdUseCase.cs

https://hackney.atlassian.net/jira/software/c/projects/DOC/boards/68?modal=detail&selectedIssue=DOC-1399
This PR refactors the method fetching document submissions and their associated claims. By introducing the group_id column, we are more easily able to link documents and claims. Therefore, instead of multiple calls to the Documents_API to fetch claims, we only need a single call. This should provide tangible performance benefits for the application.
- Added new gateway method to get claims by groupId
- Added new gateway method to get groupId by residentId & team
- Updated FindDocSubmissionsByResidentId use case to use the two new gateway methods, avoiding unneeded API calls.
- Added and updated tests for the new and refactored methods, as well as E2E tests.
This has a dependency on …

DOC-1399 - Refactor to Fetch Claims By Group Id

---

EvidenceApi/V1/UseCase/FindDocumentSubmissionsByResidentIdUseCase.cs

This will ensure that if there is no associated groupId for the resident (for example the resident has been created by a different team), it returns no documents rather than throwing an unhandled exception.

Error handling for Null GroupId

---

EvidenceApi.Tests/V1/E2ETests/ResidentsTests.cs
EvidenceApi/V1/Gateways/ResidentsGateway.cs

https://hackney.atlassian.net/browse/DOC-1413
We don't want to get a 500 when calling this endpoint with no `searchQuery` parameter, ie when using the `groupId` parameter.
Added null check operator for the parameter in the gateway.
Corrected URLs for e2e tests, as now the endpoint can effectively be called with the `groupId` parameter only.

DOC-1413: Handle possible null value to avoid 500 error

---

EvidenceApi.Tests/V1/E2ETests/BaseControllerTests.cs
EvidenceApi.Tests/V1/Gateways/ResidentsGatewayTests.cs
EvidenceApi.Tests/V1/UseCase/CreateDocumentSubmissionUseCaseTests.cs
EvidenceApi.Tests/V1/UseCase/CreateDocumentSubmissionWithoutEvidenceRequestUseCaseTests.cs
EvidenceApi/V1/Boundary/Request/ResidentRequest.cs
EvidenceApi/V1/Controllers/ResidentsController.cs
EvidenceApi/V1/Gateways/Interfaces/IResidentsGateway.cs
EvidenceApi/V1/Gateways/ResidentsGateway.cs
EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs
EvidenceApi/V1/UseCase/CreateDocumentSubmissionWithoutEvidenceRequestUseCase.cs
EvidenceApi/V1/UseCase/CreateEvidenceRequestUseCase.cs
EvidenceApi/V1/UseCase/CreateResidentUseCase.cs

https://hackney.atlassian.net/browse/DOC-1394?atlOrigin=eyJpIjoiNjhhYjdkYjFmNmNmNDkzNGI2ZGI3MTRjNjRiZmUxMDkiLCJwIjoiaiJ9
This PR changes the shape of the ResidentRequest object, allowing a groupId to be passed in from the front end. If the groupId is passed in (from an integration with an external system) then this is used in the creation of the resident. If no groupId is passed in, one is generated.
Update method signatures to allow a groupId to be passed in. In the AddResidentGroupId gateway method, check if the groupId parameter is populated. If it is, use it in the database insert.
Test in staging.

DOC-1394 - Generate GroupId Guid If Not Provided In Create Resident Request

---

.circleci/config.yml

We don't want serverless to raise above version 3 for the moment, as it will need more configuration.

Pin serverless to v3

---

EvidenceApi.Tests/V1/E2ETests/EvidenceRequestsTest.cs
EvidenceApi.Tests/V1/Gateways/EvidenceGatewayTests.cs
EvidenceApi/V1/Gateways/EvidenceGateway.cs

https://hackney.atlassian.net/browse/TS-1906
There is an issue with DES atm, whereby the evidence-api is response is exceeding the lambda payload size limit upon being called with the team only.
This PR attempts to remediate that, by returning an empty list if only the team is passed.

TS-1906: Returning an empty list if only the team is passed

---

.circleci/config.yml

This is to address the Serverless warnings we had on previous pushes.
I had done everything but unpinning the version (..hopefully).

Serverless
