LBHackney-IT/evidence-api

.gitignore, EvidenceApi.Tests/V1/E2ETests/EvidenceRequestsTest.cs, EvidenceApi.Tests/V1/Factories/DomainFactoryTests.cs, EvidenceApi.Tests/V1/Factories/EntityFactoryTest.cs, EvidenceApi.Tests/V1/Factories/ResponseFactoryTest.cs, EvidenceApi.Tests/V1/Gateways/EvidenceGatewayTests.cs, EvidenceApi.Tests/V1/Gateways/ResidentsGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/CreateEvidenceRequestUseCaseTests.cs, EvidenceApi/Migrations/20201214150433_CreateCommunications.Designer.cs, EvidenceApi/Migrations/20201214150433_CreateCommunications.cs, EvidenceApi/V1/Boundary/Response/EvidenceRequestResponse.cs, EvidenceApi/V1/Domain/Communication.cs, EvidenceApi/V1/Domain/Enums/CommunicationReason.cs, EvidenceApi/V1/Domain/Enums/DeliveryMethod.cs, EvidenceApi/V1/Domain/EvidenceRequest.cs, EvidenceApi/V1/Factories/DomainFactory.cs, EvidenceApi/V1/Factories/EntityFactory.cs, EvidenceApi/V1/Factories/ResponseFactory.cs, EvidenceApi/V1/Gateways/EvidenceGateway.cs, EvidenceApi/V1/Gateways/Interfaces/IResidentsGateway.cs, EvidenceApi/V1/Gateways/ResidentsGateway.cs, EvidenceApi/V1/Infrastructure/CommunicationEntity.cs, EvidenceApi/V1/Infrastructure/EvidenceContext.cs, EvidenceApi/V1/Infrastructure/EvidenceRequestEntity.cs, EvidenceApi/V1/Infrastructure/ResidentEntity.cs, EvidenceApi/V1/UseCase/CreateEvidenceRequest.cs, EvidenceApi/V1/UseCase/EvidenceRequestValidator.cs, bin/ef, database/schema.sql
- Implements Communication model
- Simplifies data structure and implements domain factory
https://hackney.atlassian.net/browse/DES-10
Creates data structure to allow us to implement the integration with Gov Notify.
- new Communication model (entity, domain, gateway)
- Simplifies existing models to remove complexity when converting from entity to domain
- changes DocumentTypes attribute to DocumentTypeIds
- changes Resident attribute to ResidentId
- Implements DomainFactory to easily convert entities to domain objects
None
=> DES-10 Communication Model and Domain Factory

EvidenceApi.Tests/V1/E2ETests/EvidenceRequestsTest.cs, EvidenceApi.Tests/V1/Factories/DomainFactoryTests.cs, EvidenceApi.Tests/V1/Factories/EntityFactoryTest.cs, EvidenceApi.Tests/V1/Gateways/ResidentsGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/CreateEvidenceRequestUseCaseTests.cs, EvidenceApi/Migrations/20210104115523_AddUserRequestedByToEvidenceApi.Designer.cs, EvidenceApi/Migrations/20210104115523_AddUserRequestedByToEvidenceApi.cs, EvidenceApi/V1/Boundary/Request/EvidenceRequestRequest.cs, EvidenceApi/V1/Boundary/Response/EvidenceRequestResponse.cs, EvidenceApi/V1/Domain/EvidenceRequest.cs, EvidenceApi/V1/Factories/DomainFactory.cs, EvidenceApi/V1/Factories/EntityFactory.cs, EvidenceApi/V1/Factories/ResponseFactory.cs, EvidenceApi/V1/Gateways/Interfaces/IResidentsGateway.cs, EvidenceApi/V1/Gateways/ResidentsGateway.cs, EvidenceApi/V1/Infrastructure/EvidenceRequestEntity.cs, EvidenceApi/V1/UseCase/CreateEvidenceRequestUseCase.cs, README.md, bin/dotnet, database/schema.sql
- Add UserRequestedBy field to Evidence Request
- Use Domain models when interacting with Resident Gateway
- Add some docs about modifying the database schema
https://hackney.atlassian.net/browse/DES-54
=> DES 54 store user email with evidence request

EvidenceApi.Tests/V1/Gateways/DocumentsApiGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/CreateDocumentSubmissionUseCaseTests.cs, EvidenceApi/V1/Gateways/DocumentsApiGateway.cs, EvidenceApi/V1/Gateways/Interfaces/IDocumentsApiGateway.cs, EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs
Refactored DocumentsApiGateway so the code is more readable.
=> Refactor DocumentsApiGateway

EvidenceApi.Tests/V1/UseCase/UpdateDocumentSubmissionStateUseCaseTests.cs, EvidenceApi/V1/Boundary/Response/Exceptions/BadRequestException.cs, EvidenceApi/V1/Controllers/EvidenceRequestsController.cs, EvidenceApi/V1/UseCase/UpdateDocumentSubmissionStateUseCase.cs
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-73
Added a missing test to check against changing the document submission state to an invalid one.
=> Add test to check against changing the state with an invalid one

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi.Tests/V1/E2ETests/DocumentTypesTest.cs, EvidenceApi.Tests/V1/E2ETests/EvidenceRequestsTest.cs, EvidenceApi.Tests/V1/Factories/ResponseFactoryTest.cs, EvidenceApi.Tests/V1/Gateways/NotifyGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/CreateDocumentSubmissionUseCaseTests.cs, EvidenceApi.Tests/V1/UseCase/UpdateDocumentSubmissionStateUseCaseTests.cs, EvidenceApi/DocumentTypes.json, EvidenceApi/V1/Boundary/Response/DocumentSubmissionResponse.cs, EvidenceApi/V1/Domain/DocumentType.cs, EvidenceApi/V1/Factories/ResponseFactory.cs, EvidenceApi/V1/Gateways/NotifyGateway.cs, EvidenceApi/V1/Infrastructure/AppOptions.cs, EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs, EvidenceApi/V1/UseCase/UpdateDocumentSubmissionStateUseCase.cs
- Fix magic link
- Send hydrated document type with document submission
=> Fixes for the upload flow

README.md
=> Add Swagger to Readme

EvidenceApi.Tests/V1/E2ETests/DocumentTypesTest.cs, EvidenceApi.Tests/V1/E2ETests/ResidentsTests.cs, EvidenceApi.Tests/V1/UseCase/FindResidentByIDUseCaseTests.cs, EvidenceApi/Startup.cs, EvidenceApi/V1/Controllers/EvidenceRequestsController.cs, EvidenceApi/V1/Controllers/ResidentsController.cs, EvidenceApi/V1/UseCase/FindResidentByIDUseCase.cs, EvidenceApi/V1/UseCase/Interfaces/IFindResidentByIDUseCase.cs
https://hackney.atlassian.net/browse/DES-115
Staff need to view a page about residents to view the evidence and evidence requests related to them.
- A new use case to find residents by ID
- A new controller for residents
=> DES-115 API to find Resident by ID

docs/guides/service-onboarding.md
Add a link to the JIRA ticket that the changes in this PR describe.
Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.
=> Add guide for onboarding a new service

.circleci/config.yml, .env.example, EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi.Tests/V1/Gateways/DocumentsApiGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/FindDocumentSubmissionByIdUseCaseTests.cs, EvidenceApi/V1/Boundary/Response/DocumentSubmissionResponse.cs, EvidenceApi/V1/Controllers/DocumentSubmissionsController.cs, EvidenceApi/V1/Domain/Claim.cs, EvidenceApi/V1/Domain/DocumentSubmission.cs, EvidenceApi/V1/Factories/ResponseFactory.cs, EvidenceApi/V1/Gateways/DocumentsApiGateway.cs, EvidenceApi/V1/Gateways/EvidenceGateway.cs, EvidenceApi/V1/Gateways/Interfaces/IDocumentsApiGateway.cs, EvidenceApi/V1/Infrastructure/AppOptions.cs, EvidenceApi/V1/UseCase/FindDocumentSubmissionByIdUseCase.cs, EvidenceApi/V1/UseCase/Interfaces/IFindDocumentSubmissionByIdUseCase.cs, EvidenceApi/serverless.yml
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-64
Added the fetched document from the documents API to the response of /document_submissions/id
=> Des 64 get document

EvidenceApi/serverless.yml
https://hackney.atlassian.net/browse/DES-64
Fixed a typo that was preventing authentication
=> Fix typo to fix auth

EvidenceApi.Tests/V1/E2ETests/ResidentsTests.cs, EvidenceApi.Tests/V1/Gateways/ResidentsGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/FindResidentsBySearchQueryUseCaseTests.cs, EvidenceApi/Startup.cs, EvidenceApi/V1/Controllers/ResidentsController.cs, EvidenceApi/V1/Gateways/Interfaces/IResidentsGateway.cs, EvidenceApi/V1/Gateways/ResidentsGateway.cs, EvidenceApi/V1/UseCase/FindResidentsBySearchQueryUseCase.cs, EvidenceApi/V1/UseCase/Interfaces/IFindResidentsBySearchQueryUseCase.cs
https://hackney.atlassian.net/browse/DES-131
Build API endpoint to search - add GET/residents/search
=> DES-131 search for residents

database/schema.sql
Add latest migrations step which was created in https://github.com/LBHackney-IT/evidence-api/pull/25 to schema.sql
=> Add latest migrations step to schema.sql

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi.Tests/V1/Gateways/EvidenceGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/FindDocumentSubmissionsByResidentIdUseCaseTests.cs, EvidenceApi/Startup.cs, EvidenceApi/V1/Boundary/Request/DocumentSubmissionsSearchQuery.cs, EvidenceApi/V1/Controllers/DocumentSubmissionsController.cs, EvidenceApi/V1/Gateways/EvidenceGateway.cs, EvidenceApi/V1/Gateways/Interfaces/IEvidenceGateway.cs, EvidenceApi/V1/UseCase/FindDocumentSubmissionsByResidentIdUseCase.cs, EvidenceApi/V1/UseCase/Interfaces/IFindDocumentSubmissionsByResidentIdUseCase.cs
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-145
Added a gateway function, use case, and API endpoint to get all document submissions for a resident using the resident ID.
=> Find document submissions by resident ID

terraform/production/main.tf, terraform/staging/main.tf
=> Update db version

EvidenceApi.Tests/V1/Domain/EvidenceRequestTests.cs, EvidenceApi.Tests/V1/E2ETests/EvidenceRequestsTest.cs, EvidenceApi.Tests/V1/Factories/ResponseFactoryTest.cs, EvidenceApi.Tests/V1/Gateways/EvidenceGatewayTests.cs, EvidenceApi.Tests/V1/Gateways/NotifyGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/CreateEvidenceRequestUseCaseTests.cs, EvidenceApi/Migrations/20210302123801_AddReasonColumnToEvidenceRequest.Designer.cs, EvidenceApi/Migrations/20210302123801_AddReasonColumnToEvidenceRequest.cs, EvidenceApi/V1/Boundary/Request/EvidenceRequestRequest.cs, EvidenceApi/V1/Boundary/Response/EvidenceRequestResponse.cs, EvidenceApi/V1/Domain/EvidenceRequest.cs, EvidenceApi/V1/Factories/ResponseFactory.cs, EvidenceApi/V1/Gateways/Interfaces/INotifyGateway.cs, EvidenceApi/V1/Gateways/NotifyGateway.cs, EvidenceApi/V1/UseCase/CreateEvidenceRequestUseCase.cs, README.md, database/schema.sql
https://hackney.atlassian.net/browse/DES-159
- Add Reason to EvidenceRequest domain model
- Store this in the database and pass to Notify
=> DES-159: add Reason to EvidenceRequest domain model

EvidenceApi/serverless.yml
https://hackney.atlassian.net/browse/DES-172
Increase lambda timeout to 30 seconds
=> DES-172: increase lambda timeout to 30 seconds

EvidenceApi.Tests/V1/UseCase/UpdateDocumentSubmissionStateUseCaseTests.cs, EvidenceApi/Migrations/20210318104225_AddStaffSelectedDocumentTypeId.Designer.cs, EvidenceApi/Migrations/20210318104225_AddStaffSelectedDocumentTypeId.cs, EvidenceApi/V1/Boundary/Request/DocumentSubmissionRequest.cs, EvidenceApi/V1/Boundary/Response/DocumentSubmissionResponse.cs, EvidenceApi/V1/Domain/DocumentSubmission.cs, EvidenceApi/V1/Factories/ResponseFactory.cs, EvidenceApi/V1/UseCase/UpdateDocumentSubmissionStateUseCase.cs, database/schema.sql
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-190
- Add staff selected document types on the document submission
After DES-189 is merged we need to uncomment the code that is depending on the StaffSelectedDocumentType gateway (same thing for tests)
=> Add StaffSelectedDocumentTypeId on the document submission

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi.Tests/V1/UseCase/UpdateDocumentSubmissionStateUseCaseTests.cs, EvidenceApi/V1/Boundary/Request/DocumentSubmissionUpdateRequest.cs, EvidenceApi/V1/Controllers/DocumentSubmissionsController.cs, EvidenceApi/V1/UseCase/Interfaces/IUpdateDocumentSubmissionStateUseCase.cs, EvidenceApi/V1/UseCase/UpdateDocumentSubmissionStateUseCase.cs
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-69
- Updated the request object for `UpdateDocumentSubmissionStateUseCase`
- Updated the rejection reason on the document submission if it is provided in the request
- Added a test to cover the new behaviour of the use case
- Updated tests to use the new request object
=> Add rejection reason on document submission when provided in the request

EvidenceApi.Tests/V1/Domain/ClaimTests.cs, EvidenceApi.Tests/V1/Domain/EvidenceRequestTests.cs, EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi.Tests/V1/E2ETests/EvidenceRequestsTest.cs, EvidenceApi/V1/Infrastructure/EvidenceContext.cs, EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs
https://hackney.atlassian.net/browse/DES-204
=> DES-204: Store UTC timestamps for date fields

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi.Tests/V1/Gateways/DocumentsApiGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/CreateDocumentSubmissionUseCaseTests.cs, EvidenceApi.Tests/V1/UseCase/FindDocumentSubmissionByIdUseCaseTests.cs, EvidenceApi/V1/Boundary/Response/Exceptions/DocumentsApiException.cs, EvidenceApi/V1/Controllers/DocumentSubmissionsController.cs, EvidenceApi/V1/Gateways/DocumentsApiGateway.cs, EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs, EvidenceApi/V1/UseCase/FindDocumentSubmissionByIdUseCase.cs
https://hackney.atlassian.net/browse/DES-202
=> Defensively handle DocumentAPI calls

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi.Tests/V1/Gateways/NotifyGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/UpdateDocumentSubmissionStateUseCaseTests.cs, EvidenceApi/V1/Gateways/Interfaces/INotifyGateway.cs, EvidenceApi/V1/Gateways/NotifyGateway.cs, EvidenceApi/V1/UseCase/UpdateDocumentSubmissionStateUseCase.cs, EvidenceApi/serverless.yml
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-70
Updated `UpdateDocumentSubmissionStateUseCase` to send a notification to the resident when their documents are rejected 
=> Send notification when document is rejected

EvidenceApi/EvidenceApi.csproj, nuget.config
https://hackney.atlassian.net/browse/DES-203
=> DES-203: Import GOV.UK Notify from Nuget

EvidenceApi.Tests/V1/Gateways/ResidentsGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/ResidentRequestValidatorTests.cs, EvidenceApi/V1/UseCase/ResidentRequestValidator.cs
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-157
Updated resident information validation and updated the tests to reflect the new behaviour
=> DES-157 Update resident information validation and added tests

EvidenceApi/DocumentTypes.json, EvidenceApi/StaffSelectedDocumentTypes.json
https://hackney.atlassian.net/browse/DES-219
=> DES-219: add Security_Team group

.env.example, EvidenceApi.Tests/V1/Gateways/DocumentsApiGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/UpdateDocumentSubmissionStateUseCaseTests.cs, EvidenceApi/V1/Boundary/Request/ClaimRequest.cs, EvidenceApi/V1/Boundary/Request/ClaimUpdateRequest.cs, EvidenceApi/V1/Boundary/Request/DocumentSubmissionUpdateRequest.cs, EvidenceApi/V1/Controllers/DocumentSubmissionsController.cs, EvidenceApi/V1/Domain/Claim.cs, EvidenceApi/V1/Gateways/DocumentsApiGateway.cs, EvidenceApi/V1/Gateways/Interfaces/IDocumentsApiGateway.cs, EvidenceApi/V1/Infrastructure/AppOptions.cs, EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs, EvidenceApi/V1/UseCase/Interfaces/ICreateDocumentSubmission.cs, EvidenceApi/V1/UseCase/Interfaces/IUpdateDocumentSubmissionStateUseCase.cs, EvidenceApi/V1/UseCase/UpdateDocumentSubmissionStateUseCase.cs, EvidenceApi/serverless.yml
https://hackney.atlassian.net/browse/DES-192
=> DES-192: call DocumentsApi to update the claim

EvidenceApi/DocumentTypes.json, EvidenceApi/StaffSelectedDocumentTypes.json
https://hackney.atlassian.net/browse/DES-219
=> DES-219: add Security_Testing group

.circleci/config.yml
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-252
Changed the CircleCI config to deploy the staging environment to a new AWS account.
=> Change circleci config to deploy to a new aws account

.circleci/config.yml
Updated CircleCI configuration to assume a new IAM role
=> Update IAM role to be assumed by circleci

.circleci/config.yml, terraform/staging/main.tf
- Remove parallelism between deploy-to staging job and terraform-init-and-apply-to-staging job
- Update state bucket name in terraform file
=> Change CircleCI config and update terraform bucket name

terraform/staging/main.tf
Updated the VPC name and subnets
=> Update vpc name and subnets

EvidenceApi/serverless.yml
https://hackney.atlassian.net/browse/DES-252
=> DES-252: updated staging vpc security group and subnets

.circleci/config.yml
https://hackney.atlassian.net/browse/DES-252
=> DES-252: update jumpbox SSM param names

EvidenceApi/serverless.yml
https://hackney.atlassian.net/browse/DES-252
=> DES-252: use evidence_api_db_traffic-stg

.circleci/config.yml, EvidenceApi/serverless.yml
- Uncomment production config
- Update security group and subnets
=> Uncomment production config and update security group and subnets

docs/adr/0006-use-palos-altos-to-perform-malware-scanning.md, docs/adr/README.md
https://hackney.atlassian.net/browse/DES-178
=> DES-178: ADR

EvidenceApi/DocumentTypes.json, EvidenceApi/StaffSelectedDocumentTypes.json
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-280
Add document types and staff selected document types for Repairs Contact Centre and Electoral Services
=> Add document types for Repairs and Electoral

EvidenceApi/Startup.cs
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-249
- Add security header based on the feedback received from the security assessment
=> Add security header

EvidenceApi/EvidenceApi.csproj, EvidenceApi/Startup.cs, EvidenceApi/serverless.yml
https://hackney.atlassian.net/browse/DES-226
=> DES-226: Enable AWS X-Ray

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi.Tests/V1/UseCase/CreateEvidenceRequestUseCaseTests.cs, EvidenceApi.Tests/V1/UseCase/UpdateDocumentSubmissionStateUseCaseTests.cs, EvidenceApi/Startup.cs, EvidenceApi/V1/UseCase/CreateEvidenceRequestUseCase.cs, EvidenceApi/V1/UseCase/UpdateDocumentSubmissionStateUseCase.cs
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-225
Replace console logs with logger
=> Replace console logs with logger

EvidenceApi.Tests/V1/E2ETests/EvidenceRequestsTest.cs, EvidenceApi.Tests/V1/UseCase/ResidentRequestValidatorTests.cs, EvidenceApi/V1/UseCase/CreateEvidenceRequestUseCase.cs, EvidenceApi/V1/UseCase/ResidentRequestValidator.cs
https://hackney.atlassian.net/browse/DES-315
=> DES-315: remove email validation which was causing issues

README.md
Add the MIT license because it's a requirement for the service assessment
=> Refer to license from README

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi.Tests/V1/Gateways/DocumentsApiGatewayTests.cs, EvidenceApi/V1/Gateways/DocumentsApiGateway.cs
So they're included in the S3 upload
https://hackney.atlassian.net/browse/DES-309
=> DES-309: provide Content-Type to DocumentsApi

EvidenceApi/serverless.yml
See https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html
=> DES-309: configure API Gateway to accept binary media types

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi.Tests/V1/Gateways/DocumentsApiGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/CreateDocumentSubmissionUseCaseTests.cs, EvidenceApi/V1/Boundary/Request/DocumentUploadRequest.cs, EvidenceApi/V1/Controllers/EvidenceRequestsController.cs, EvidenceApi/V1/Gateways/DocumentsApiGateway.cs, EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs, EvidenceApi/V1/UseCase/Interfaces/ICreateDocumentSubmission.cs
Add a link to the JIRA ticket that the changes in this PR describe.
Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.
=> DES-309: test uploading document in base64

EvidenceApi.Tests/V1/UseCase/UpdateDocumentSubmissionStateUseCaseTests.cs, EvidenceApi/V1/UseCase/UpdateDocumentSubmissionStateUseCase.cs
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-319
Removed the ability to change document submission state when it has already been accepted or rejected
=> Remove ability to change document submission state when accepted or rejected

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi.Tests/V1/Gateways/DocumentsApiGatewayTests.cs, EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs, EvidenceApi/serverless.yml
https://hackney.atlassian.net/browse/DES-309
=> DES-309: uncomment out tests

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi.Tests/V1/Factories/ResponseFactoryTest.cs, EvidenceApi.Tests/V1/UseCase/UpdateDocumentSubmissionStateUseCaseTests.cs, EvidenceApi/Migrations/20210625135512_AddRejectedAtAndUserToDocumentSubmission.Designer.cs, EvidenceApi/Migrations/20210625135512_AddRejectedAtAndUserToDocumentSubmission.cs, EvidenceApi/V1/Boundary/Request/DocumentSubmissionUpdateRequest.cs, EvidenceApi/V1/Boundary/Response/DocumentSubmissionResponse.cs, EvidenceApi/V1/Domain/DocumentSubmission.cs, EvidenceApi/V1/Factories/ResponseFactory.cs, EvidenceApi/V1/UseCase/UpdateDocumentSubmissionStateUseCase.cs
https://hackney.atlassian.net/browse/DES-281
=> DES-281: add rejected time and the user to document submission

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi/Migrations/20210628145051_UpdateRejectedAtToBeOptionalDocumentSubmission.Designer.cs, EvidenceApi/Migrations/20210628145051_UpdateRejectedAtToBeOptionalDocumentSubmission.cs, EvidenceApi/V1/Domain/DocumentSubmission.cs
https://hackney.atlassian.net/browse/DES-281
=> DES-281: DocumentSubmission RejectedAt should be optional

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi.Tests/V1/Factories/ResponseFactoryTest.cs, EvidenceApi/V1/Boundary/Response/DocumentSubmissionResponse.cs, EvidenceApi/V1/Factories/ResponseFactory.cs, EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs, EvidenceApi/V1/UseCase/FindDocumentSubmissionByIdUseCase.cs, EvidenceApi/V1/UseCase/FindDocumentSubmissionsByResidentIdUseCase.cs, EvidenceApi/V1/UseCase/UpdateDocumentSubmissionStateUseCase.cs
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-316
- Added `validUntil` to the document submission response
- Adjusted tests
=> Add validity date to the document submission response

docs/diagrams/evidence-request-creation-sequence-flow.iuml, docs/diagrams/evidence-request-creation-sequence-flow.svg, docs/diagrams/resident-sequence-flow.iuml, docs/diagrams/resident-sequence-flow.svg, docs/diagrams/review-document-sequence-flow.iuml, docs/diagrams/review-document-sequence-flow.svg
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-313
Added PlantUML diagrams for primary sequence flow from the [Miro board](https://miro.com/app/board/o9J_kgEWTBE=/?moveToWidget=3074457351740324420&cot=12) and updated it:
- evidence creation flow
- resident flow
- review document flow
=> Add PlantUML diagrams for primary sequence flow

EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs
https://hackney.atlassian.net/jira/software/projects/DES/boards/45/backlog?selectedIssue=DES-117
Refactor use case to catch only documents-api specific error.
=> Refactor use case

EvidenceApi.Tests/V1/UseCase/UpdateDocumentSubmissionStateUseCaseTests.cs, EvidenceApi/V1/Gateways/DocumentsApiGateway.cs, EvidenceApi/V1/UseCase/UpdateDocumentSubmissionStateUseCase.cs
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-332
- Refactored the exception thrown by documents-api when it can't update the claim
=> Refactor exception thrown by documents-api for updating the claim

EvidenceApi/DocumentTypes.json, EvidenceApi/StaffSelectedDocumentTypes.json
Added configuration for Housing Register team
Jira card: https://hackney.atlassian.net/browse/DES-337
=> Add configuration for Housing Register team

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi.Tests/V1/Factories/ResponseFactoryTest.cs, EvidenceApi/V1/Boundary/Response/DocumentSubmissionResponse.cs, EvidenceApi/V1/Factories/ResponseFactory.cs
https://hackney.atlassian.net/browse/DES-325
Added retention to document submission response so we can show it in the UI.
=> Add retention to document submission response

EvidenceApi.Tests/V1/Gateways/ResidentsGatewayTests.cs, EvidenceApi/V1/Gateways/ResidentsGateway.cs
https://hackney.atlassian.net/browse/DES-343
=> DES-343: Resident search should be case insensitive

EvidenceApi.Tests/V1/E2ETests/BaseControllerTests.cs, EvidenceApi.Tests/V1/Gateways/DocumentTypeGatewayTests.cs, EvidenceApi.Tests/V1/Gateways/NotifyGatewayTests.cs, EvidenceApi.Tests/V1/Gateways/StaffSelectedDocumentTypeGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/CreateDocumentSubmissionUseCaseTests.cs, EvidenceApi.Tests/V1/UseCase/UpdateDocumentSubmissionStateUseCaseTests.cs, EvidenceApi/Migrations/20210914093118_AddNotificationEmailColumnToEvidenceRequest.Designer.cs, EvidenceApi/Migrations/20210914093118_AddNotificationEmailColumnToEvidenceRequest.cs, EvidenceApi/V1/Boundary/Request/EvidenceRequestRequest.cs, EvidenceApi/V1/Domain/Enums/CommunicationReason.cs, EvidenceApi/V1/Domain/EvidenceRequest.cs, EvidenceApi/V1/Gateways/DocumentTypeGateway.cs, EvidenceApi/V1/Gateways/Interfaces/IDocumentTypeGateway.cs, EvidenceApi/V1/Gateways/Interfaces/INotifyGateway.cs, EvidenceApi/V1/Gateways/NotifyGateway.cs, EvidenceApi/V1/Gateways/StaffSelectedDocumentTypeGateway.cs, EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs, EvidenceApi/V1/UseCase/CreateEvidenceRequestUseCase.cs, EvidenceApi/V1/UseCase/UpdateDocumentSubmissionStateUseCase.cs
https://hackney.atlassian.net/browse/DES-323
- Added an email notification to the staff member that created an evidence request when the resident uploads document(s)
=> Des 323 notify staff

EvidenceApi/serverless.yml
https://hackney.atlassian.net/browse/DES-323
Changed wrong parameter for document uploaded notification.
=> Change parameter for document uploaded notification

.circleci/config.yml, .config/dotnet-tools.json, EvidenceApi/EvidenceApi.csproj, EvidenceApi/Startup.cs, EvidenceApi/publish-to-swagger-hub.sh
https://hackney.atlassian.net/browse/DES-143
Builds on https://github.com/LBHackney-IT/cv-19-res-support-v3/pull/69 and extends it to invoke `publish-to-swagger-hub.sh` from CircleCI after `deploy-to-production` finishes successfully
=> DES-143: Publish Swagger docs on production deployment

.circleci/config.yml
https://hackney.atlassian.net/browse/DES-143
=> DES-143: correct folder name

database/Dockerfile
Change postgres docker image to check if it fixes the build errors.
=> Change postgres image to fix the errors

EvidenceApi/DocumentTypes.json, EvidenceApi/StaffSelectedDocumentTypes.json
https://hackney.atlassian.net/browse/DOC-261
Added configuration for the demo team
=> Add configuration for demo team

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi.Tests/V1/E2ETests/DocumentTypesTest.cs, EvidenceApi.Tests/V1/Gateways/NotifyGatewayTests.cs, EvidenceApi/DocumentTypes.json
https://hackney.atlassian.net/browse/DOC-297
Updated the configuration of the document types for the Development Housing Team to contain only document types
=> Change document types configuration for Development Housing Team

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi.Tests/V1/E2ETests/DocumentTypesTest.cs, EvidenceApi.Tests/V1/Gateways/NotifyGatewayTests.cs, EvidenceApi/DocumentTypes.json
Reverts LBHackney-IT/evidence-api#119
=> Revert "Change document types configuration for Development Housing Team"

EvidenceApi/DocumentTypes.json, EvidenceApi/StaffSelectedDocumentTypes.json
https://hackney.atlassian.net/browse/DOC-384
Update Housing Register team configuration with more document types and staff selected document types
=> Update Housing Register team configuration

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi.Tests/V1/UseCase/CreateDocumentSubmissionUseCaseTests.cs, EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs
https://hackney.atlassian.net/browse/DOC-536
Added a validation check on the request to create a document submission to prevent a security issue with the base64 encoded document.
=> Add validation for the document in base64 mime type

.env.example, EvidenceApi/V1/Controllers/EvidenceRequestsController.cs, EvidenceApi/V1/Domain/S3UploadPolicy.cs, EvidenceApi/V1/Gateways/DocumentsApiGateway.cs, EvidenceApi/V1/Gateways/Interfaces/IDocumentsApiGateway.cs, EvidenceApi/V1/Infrastructure/AppOptions.cs, EvidenceApi/serverless.yml
https://hackney.atlassian.net/browse/DOC-417
Created a spike for calling documents-api to create a pre-sgined upload URL to upload files to S3
=> Add spike to call documents api to create a presigned url

EvidenceApi/V1/Controllers/EvidenceRequestsController.cs
https://hackney.atlassian.net/browse/DOC-417
Fixed typo in the controller related to the path to create a pre-signed URL
=> Fix typo in the controller

EvidenceApi.Tests/V1/E2ETests/DocumentSubmissionsTest.cs, EvidenceApi.Tests/V1/Factories/ResponseFactoryTest.cs, EvidenceApi/V1/Boundary/Response/DocumentSubmissionResponse.cs, EvidenceApi/V1/Controllers/EvidenceRequestsController.cs, EvidenceApi/V1/Factories/ResponseFactory.cs, EvidenceApi/V1/Gateways/DocumentsApiGateway.cs, EvidenceApi/V1/Gateways/Interfaces/IDocumentsApiGateway.cs, EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs, EvidenceApi/V1/UseCase/FindDocumentSubmissionByIdUseCase.cs, EvidenceApi/V1/UseCase/FindDocumentSubmissionsByResidentIdUseCase.cs
https://hackney.atlassian.net/browse/DOC-417
Updated CreateDocumentSubmission flow to request a pre-signed URL using documents-api
=> Update CreateDocumentSubmission flow to request pre-signed URL

README.md
This PR updates the README for evidence-api to include instructions about getting the envars and how to set up the local db.
Changed the instructions because the make commands were not working.
=> Readme update for start up, testing and accepted MIME types

EvidenceApi.Tests/V1/E2ETests/BaseControllerTests.cs, EvidenceApi.Tests/V1/E2ETests/EvidenceRequestsTest.cs, EvidenceApi.Tests/V1/Factories/ResponseFactoryTest.cs, EvidenceApi.Tests/V1/UseCase/CreateEvidenceRequestUseCaseTests.cs, EvidenceApi/Migrations/20220406140948_AddNoteToResident.Designer.cs, EvidenceApi/Migrations/20220406140948_AddNoteToResident.cs, EvidenceApi/V1/Boundary/Request/EvidenceRequestRequest.cs, EvidenceApi/V1/Boundary/Response/EvidenceRequestResponse.cs, EvidenceApi/V1/Domain/EvidenceRequest.cs, EvidenceApi/V1/Factories/ResponseFactory.cs, EvidenceApi/V1/UseCase/CreateEvidenceRequestUseCase.cs, README.md, database/schema.sql
https://hackney.atlassian.net/browse/DOC-680
- Added NoteToResident attribute to EvidenceRequest domain model
- Added database migration and updated the schema to contain NoteToResident
- Updated request and response boundaries with NoteToResident
- Updated CreateEvidenceRequestUseCase
- Updated response factory with NoteToResident
- Updated unit tests and integration tests with NoteToResident
=> Add NoteToResident to EvidenceRequest

EvidenceApi/DocumentTypes.json, EvidenceApi/StaffSelectedDocumentTypes.json
https://hackney.atlassian.net/browse/DOC-685
Adding config for Admission and Pupil Benefits (School's Admissions).
- Added document types
- Added staff-selected document types
=> Add Admission and Pupil Benefits config as part of onboarding

EvidenceApi/V1/UseCase/UpdateEvidenceRequestStateUseCase.cs
https://hackney.atlassian.net/browse/DOC-836
Updated the way the evidence request state is computed so it doesn't depend on document types.
=> Update evidence request state calculation

EvidenceApi.Tests/V1/Gateways/EvidenceGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/CreateDocumentSubmissionUseCaseTests.cs, EvidenceApi.Tests/V1/UseCase/FindDocumentSubmissionsByResidentIdUseCaseTests.cs, EvidenceApi.Tests/V1/UseCase/UpdateEvidenceRequestStateUseCaseTests.cs, EvidenceApi/V1/Gateways/DocumentsApiGateway.cs, EvidenceApi/V1/Gateways/EvidenceGateway.cs, EvidenceApi/V1/Gateways/Interfaces/IDocumentsApiGateway.cs, EvidenceApi/V1/Gateways/Interfaces/IEvidenceGateway.cs, EvidenceApi/V1/UseCase/CreateDocumentSubmissionUseCase.cs, EvidenceApi/V1/UseCase/FindDocumentSubmissionsByResidentIdUseCase.cs, EvidenceApi/V1/UseCase/UpdateEvidenceRequestStateUseCase.cs
https://hackney.atlassian.net/browse/DOC-988
Improved the performance of the API by:
- fetching all document submissions attached to an evidence request with a single call to the database
- making concurrent calls to Documents API to get claims for documents
- throttling Evidence API to make only 20 API requests to Documents API when getting claims for documents to prevent exhausting all of the database connections
Monitor the time of the requests and adjust the added throttle as needed.
=> Improve api performance

docs/guides/tracking-requests.md
Added additional commands for connecting to different dbs in different environments, to save developer time trying to connect.
=> Adding additional commands for connecting to different dbs and envs

EvidenceApi.Tests/V1/Gateways/EvidenceGatewayTests.cs, EvidenceApi/V1/Gateways/EvidenceGateway.cs
https://hackney.atlassian.net/browse/DOC-1089
We need to order the evidence requests and document submissions in the Resident page
There was a previous PR about this but it impacted the wrong gateway function
This PR aims to roll back those changes and introduce new ones
Changes in gateway functions
Adapted pre-existent gateway tests and helper
N/A
=> Doc-1089: Sorting evidence requests and document submissions in the Resident page

EvidenceApi/DocumentTypes.json, EvidenceApi/StaffSelectedDocumentTypes.json
Part of testing this ticket in staging https://hackney.atlassian.net/browse/DOC-872
We need to check if the enabled flag works properly as expected.
Added two new configs for doc types and staff selected doc types.
Make an evidence request in staging. Then make new PR turning those doc types to false.
=> Adding new doc type and staff selected doc type to dev team config

docs/adr/0007-use-s3-for-uploading-and-fetching-documents.md, docs/adr/0008-create-a-document-submission-without-a-parent-evidence-request.md, docs/adr/README.md
We've made some architectural decisions in the past few months that need to be recorded. This includes using the S3 API and uploading against a resident.
Added new ADRs
=> New adrs for S3 upload/fetch and upload against a resident

EvidenceApi/V1/UseCase/CreateDocumentSubmissionWithoutEvidenceRequestUseCase.cs
https://hackney.atlassian.net/browse/DOC-1277
Add `AcceptedAt` value to the document submission created without an evidence request to keep the database consistent (if we have an accepted state we also have an `AcceptedAt` value)
=> Add AcceptedAt to the document submission created without an evidence request

EvidenceApi.Tests/V1/UseCase/FindDocumentSubmissionByIdUseCaseTests.cs, EvidenceApi/V1/UseCase/FindDocumentSubmissionByIdUseCase.cs
https://hackney.atlassian.net/browse/DOC-1279
Get team from document submission instead of evidence request as not all documents submission have an evidence request associated to them anymore.
=> Get team from document submission instead of evidence request

EvidenceApi.Tests/V1/E2ETests/ResidentsTests.cs, EvidenceApi.Tests/V1/Gateways/ResidentsGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/CreateResidentUseCaseTests.cs, EvidenceApi/Startup.cs, EvidenceApi/V1/Controllers/ResidentsController.cs, EvidenceApi/V1/Gateways/Interfaces/IResidentsGateway.cs, EvidenceApi/V1/Gateways/ResidentsGateway.cs, EvidenceApi/V1/UseCase/CreateResidentUseCase.cs, EvidenceApi/V1/UseCase/Interfaces/ICreateResidentUseCase.cs, EvidenceApi/V1/Validators/ResidentRequestValidator.cs
https://hackney.atlassian.net/browse/DOC-1345
Added a new endpoint to be able to create new residents.
- Added a gateway function to create a resident
- Added a use case to create a resident
- Added a new endpoint to create a resident
- Added unit and integration tests
=> Add endpoint to create a new resident

EvidenceApi.Tests/TestDataHelper.cs, EvidenceApi.Tests/V1/Gateways/EvidenceGatewayTests.cs, EvidenceApi/Migrations/20221208153507_AddIsHiddenFlagToDocumentSubmission.Designer.cs, EvidenceApi/Migrations/20221208153507_AddIsHiddenFlagToDocumentSubmission.cs, EvidenceApi/V1/Domain/DocumentSubmission.cs, EvidenceApi/V1/Gateways/EvidenceGateway.cs
https://hackney.atlassian.net/browse/DOC-1374
Add a flag to the document submission which can be used to decide whether we want to display it in the UI or not.
=> Add flag to document submission so we can hide it in FE

EvidenceApi/DocumentTypes.json, EvidenceApi/StaffSelectedDocumentTypes.json
https://hackney.atlassian.net/browse/DOC-1381
Adding the necessary configuration to onboard Parking Services to use DES
Config JSON files
=> DOC-1381: Onboarding Parking Services

EvidenceApi.Tests/V1/Gateways/ResidentsGatewayTests.cs, EvidenceApi/V1/Gateways/Interfaces/IResidentsGateway.cs, EvidenceApi/V1/Gateways/ResidentsGateway.cs, EvidenceApi/V1/UseCase/CreateResidentUseCase.cs
https://hackney.atlassian.net/browse/DOC-1403
This PR adds a new record to the previously created resident_team_group_id table, associating a resident to a group_id. This sets the groundwork for further tickets in the epic.
Below image shows successful creation of new record after creating a resident:
=> DOC-1403 - Add new record to resident_team_group_id table upon creating a resident

EvidenceApi/V1/Controllers/ClaimsBackfillController.cs
https://hackney.atlassian.net/jira/software/c/projects/DOC/boards/68?selectedIssue=DOC-1398
This is an interim PR to test out whether the generation of the new API access token has been successful.
=> DOC-1398 - Test API Key Generation

EvidenceApi/StaffSelectedDocumentTypes.json
[Jira ticket](https://hackney.atlassian.net/jira/software/c/projects/DOC/boards/68?modal=detail&selectedIssue=DOC-1409) 
Reorganising JSON so document types are alphabetical
HR team struggle to find the doc types they look for
Reorganising JSON
Deploy and check in staging
=> DOC-1409 - Reorganise staff selected docs alphabetically

EvidenceApi/Migrations/20230206153010_BackfillResidentsGroupIdWithExistingResidents.Designer.cs, EvidenceApi/Migrations/20230206153010_BackfillResidentsGroupIdWithExistingResidents.cs
…ing residents
https://hackney.atlassian.net/browse/DOC-1412
=> DOC-1412 - Manual Backfill of Existing Residents to ResidentGroupIdTable

EvidenceApi.Tests/V1/Gateways/EvidenceGatewayTests.cs, EvidenceApi/V1/UseCase/FindDocumentSubmissionsByResidentIdUseCase.cs
=> DOC-1399 - Revert fetching method

EvidenceApi/V1/UseCase/FindDocumentSubmissionsByResidentIdUseCase.cs
This restores the method for fetching claims by group Id.
=> restore refactored doc fetching method

EvidenceApi.Tests/TestDataHelper.cs, EvidenceApi.Tests/V1/E2ETests/ResidentsTests.cs, EvidenceApi.Tests/V1/Gateways/ResidentsGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/FindResidentsBySearchQueryUseCaseTests.cs, EvidenceApi/V1/Boundary/Request/ResidentSearchQuery.cs, EvidenceApi/V1/Gateways/Interfaces/IResidentsGateway.cs, EvidenceApi/V1/Gateways/ResidentsGateway.cs, EvidenceApi/V1/UseCase/FindResidentsBySearchQueryUseCase.cs
https://hackney.atlassian.net/browse/DOC-1397
We need to retrieve a resident associated to a groupId and a team on the new table
Changed request object, usecase and gateway and associated tests
=> DOC-1397: Get resident by groupId

EvidenceApi/DocumentTypes.json
https://hackney.atlassian.net/browse/DOC-1381
The users asked to use _Photographs_ instead of _Photograph_ as one of the `documentTypes`.
Changed one word in a JSON file.
=> DOC-1381: Update documentTypes as per user's specification

EvidenceApi.Tests/V1/E2ETests/ResidentsTests.cs, EvidenceApi.Tests/V1/Gateways/DocumentsApiGatewayTests.cs, EvidenceApi.Tests/V1/Gateways/ResidentsGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/AmendResidentGroupIdUseCaseTests.cs, EvidenceApi/Startup.cs, EvidenceApi/V1/Boundary/Request/ClaimsUpdateRequest.cs, EvidenceApi/V1/Boundary/Request/ResidentGroupIdRequest.cs, EvidenceApi/V1/Controllers/ResidentsController.cs, EvidenceApi/V1/Gateways/DocumentsApiGateway.cs, EvidenceApi/V1/Gateways/Interfaces/IDocumentsApiGateway.cs, EvidenceApi/V1/Gateways/Interfaces/IResidentsGateway.cs, EvidenceApi/V1/Gateways/ResidentsGateway.cs, EvidenceApi/V1/UseCase/AmendResidentGroupIdUseCase.cs, EvidenceApi/V1/UseCase/Interfaces/IAmendResidentGroupIdUseCase.cs
https://hackney.atlassian.net/browse/DOC-1352
- Added endpoint to update `groupId` for a resident and their claims (including use case and gateway functions)
- Added unit and integration tests
=> Add endpoint, use case and gateway functions to update groupId for a resident and their claims

EvidenceApi.Tests/V1/Gateways/EvidenceGatewayTests.cs, EvidenceApi/V1/Gateways/EvidenceGateway.cs
https://hackney.atlassian.net/jira/software/c/projects/DOC/boards/68?modal=detail&selectedIssue=DOC-1416
This is a small PR that ensures any document submissions with the is_hidden flag set to true are not returned in the query for document submissions.
=> DOC-1416 - Add Filter To Not Return Documents That Have Been Hidden

EvidenceApi.Tests/V1/E2ETests/ResidentsTests.cs, EvidenceApi/V1/Gateways/ResidentsGateway.cs
Add a link to the JIRA ticket that the changes in this PR describe.
Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.
=> Hide hidden residents, and make sure the right resident is picked when merging

EvidenceApi.Tests/V1/E2ETests/ResidentsTests.cs, EvidenceApi.Tests/V1/Gateways/ResidentsGatewayTests.cs, EvidenceApi.Tests/V1/UseCase/EditResidentUseCaseTests.cs, EvidenceApi/Startup.cs, EvidenceApi/V1/Boundary/Request/EditResidentRequest.cs, EvidenceApi/V1/Controllers/ResidentsController.cs, EvidenceApi/V1/Gateways/Interfaces/IResidentsGateway.cs, EvidenceApi/V1/Gateways/ResidentsGateway.cs, EvidenceApi/V1/UseCase/EditResidentUseCase.cs, EvidenceApi/V1/UseCase/Interfaces/IEditResidentUseCase.cs
https://hackney.atlassian.net/browse/DOC-1417
Added a new endpoint to edit a resident.
- Added a new use case
- Updated the gateway function that creates residents
- Added a new request object
- Added unit and integration tests
=> Add endpoint to edit a resident

EvidenceApi.Tests/V1/Gateways/ResidentsGatewayTests.cs, EvidenceApi/V1/Gateways/ResidentsGateway.cs
Add a link to the JIRA ticket that the changes in this PR describe.
Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.
=> Make sure resident is hidden on search when soft deleted

EvidenceApi/V1/UseCase/MergeAndLinkResidentsUseCase.cs
Remove comments in the use case
=> Remove comments

docs/guides/tracking-requests.md
https://hackney.atlassian.net/browse/TS-1215
This is a dummy PR to check the pipeline still works after some Cloud changes.
Corrections to a README file.
=> TS-1215: Updates to readme for tracking request

.circleci/config.yml
=> Upgrade Node version

EvidenceApi/serverless.yml
`usagePlan` is not really needed here and it upsets Serverless
=> Serverless - deleting unneeded property that raises a warning

EvidenceApi/serverless.yml
Update authorizer ARN to point to new authorizer
=> Update authorizer ARN
